### PR TITLE
Near last fixes

### LINKED ISSUE #306: Update Help Strings for Undo/Redo/History Commands

### LINKED ISSUE #307: Get rid of unused methods (Refactor)

### LINKED ISSUE #334: Commands entered are occasionally called twice
This is a UI issue and comes with the latest merge into master. 

Have discussed this with @Joanna-YJA on Tele.

### LINKED ISSUE #335: Import Command (not completely successfully executed) does not result in persisted data state
Hence, any subsequent calls to history/undo/redo are not shown properly.

### LINKED ISSUE #336: Deprecate Debug Statements/Methods in ModelHistory and CommandHistory Classes

### PR DESCRIPTION
**Pull request by brianyenna**
## Description
Describe the pull request and what it does
1. What is this implementing
Closes #336, deprecatign debug statements
Closes #335, as per John's identification of the bug. Basically ensures that even if the import command is not completely successfully executed, the data is still persisted in model history.This is necessary because the import command actually allows some of the data to go into model even when some of the data in the csv file is incorrect/incorrectly formatted. 
Closes #334, this is a UI bug, where previously all KeyEvents were handled (leading to multiple handling when KeyPress and KeyRelease are detected)
Closes #307, gets rid of unused methods in ModelHistory 
Closes #306, by updating help strings for undo/redo/history commands. 

2. How is it being implemented
3. Why is this being implemented

## Checks
- [X] No errors when running the tests
- [X] Build and checkstyle passes
- [X] Run the app and ran 2 commands without failing
- [X] Written the baseline test cases for the PR

## Changelog
- []
- []
- []

### CODE REVIEW

File: src/main/java/seedu/address/logic/Logic.java [hunk 1]
```diff
@@ -80,15 +78,8 @@
...
-     * Returns a List of Strings describing the commands that can be undone.
+     * Get statistics on EntityLists.
      */
-    List<String> getUndoCommandHistory();
-
-    /**
-     * Returns a List of Strings describing the commands that can be redone.
-     */
-    List<String> getRedoCommandHistory();
-
```
Comment (hcwong) [inline src/main/java/seedu/address/logic/Logic.java]: Context for this removal?

File: src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java [hunk 2]
```diff
@@ -50,12 +50,12 @@ public CommandResult execute(Model model) throws CommandException {
...
         try {
             model.removeMentorFromTeam(teamId, mentorToBeRemoved);
-            model.updateHistory(this);
-            model.recordCommandExecution(this.getCommandInputString());
         } catch (AlfredException e) {
             throw new CommandException(MESSAGE_TEAM_DOES_NOT_HAVE_MENTOR);
         }
 
+        model.updateHistory(this);
+        model.recordCommandExecution(this.getCommandInputString());
```
Comment (hcwong) [inline src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java]: Should provide some context on this move

Comment (hcwong) [reply src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java]: Is it to make it always run?

File: src/main/java/seedu/address/logic/Logic.java (hunk 1 above)
Comment (brianyenna) [reply src/main/java/seedu/address/logic/Logic.java]: it's no longer used. It was for debugging, really. Cos I pritned the string in the command box

File: src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java (hunk 2 above)
Comment (brianyenna) [reply src/main/java/seedu/address/logic/commands/removecommand/RemoveMentorCommand.java]: it's moved outside of the try-catch block because model history and command history are only updated when the command is successfully executed.
