### PR TITLE
Fix storage bugs

### LINKED ISSUE #118: Fix saving team list bug in storage
Every time ModelManager tries to save TeamList, it will encounter an error (NullPointerException) if the Optional<Mentor> object in the Team is empty. This is a rather essential feature and needs to be fixed urgently so that the team can continue working on the rest of their features without dealing with this pesky error.

### LINKED ISSUE #119: Clean up exception handling and throwing in storage
Right now the exception handling in the Storage classes is messy and there are significant overlaps in the exceptions being thrown. This should be cleaned up, to improve the quality of the code.

### LINKED ISSUE #120: Strengthen validation of objects read from storage
Right now, the Storage code has a very basic but nonetheless important validation of the objects read from the JSON files. It will take the fields read from the JSON file and check if they are valid by calling the field class' isValid() method. 

It would be good to improve the validation of the objects read from storage to prevent malicious/inadvertent tampering of the JSON data from breaking the Alfred app:
1. Check for duplication
2. Check that the Participants and Mentors in each Team object in the TeamList actually exist in the loaded ParticipantList

### PR DESCRIPTION
**Pull request by brianyenna**
## Description
Describe the pull request and what it does
1. What is this implementing
This PR targets the following issues:
#118 
Previously, there was a problem saving TeamList to storage because the code did not handle the case where the Optional<Mentor> field in the Team object was empty. This PR fixes #118.

#119 
Enhancement to the storage code to improve exception handling and throwing. This PR makes the exception handling and throwing cleaner and more consistent. This PR closes #119 

#120 
Enhancement to the storage code to reduce the chances of inadvertent/malicious tampering of the JSON file causing problems for Alfred. This PR fixes #120, implementing checking for duplicate objects and checking for the existence of the mentor and participants in the team objects. 

2. How is it being implemented
For #118, a separate case for handling the empty case was done. 
For #119, removal of unnecessary exceptions was done. Cleaned up the exceptions thrown as well. 
For #120, checking of duplication was done in the toModelType() method of the JsonSerializableStorage classes, and checking for existent of mentor and particiapnts in the team objects was done in ModelManager. 
3. Why is this being implemented
Refer to the issues for their importance. 

## Checks
- [X] No errors when running the tests
- [X] Build and checkstyle passes
- [X] Run the app and ran 2 commands without failing
- [] Written the baseline test cases for the PR

## Changelog
- []
- []
- []

## Comments for Reviewer (if any)
@hcwong, made some changes to model. For your review.

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -125,11 +113,39 @@ public void initialize() {
...
-        } catch (IOException | AlfredException e) {
-            logger.warning("MentorList is empty in storage. Writing a new one.");
+        } catch (AlfredException e) {
+            logger.warning("Initialising new MentorList. "
+                           + "Problem encountered reading MentorList from storage: " + e.getMessage());
             this.mentorList = new MentorList();
         }
 
+        try {
+            Optional<TeamList> storageTeamList = this.storage.readTeamList();
```
Comment (hcwong) [inline src/main/java/seedu/address/model/ModelManager.java]: Any reason why this is shifted down? Or just for stylistic reasons?
